FROM node:22-alpine

WORKDIR /app

# Instalar pnpm
RUN npm install -g pnpm

# Copiar archivos de dependencias
COPY package.json pnpm-lock.yaml ./

# Instalar dependencias
RUN pnpm install

# Copiar el resto del código
COPY . .

# Exponer puerto de Vite
EXPOSE 80

# El comando se ejecutará desde docker-compose
CMD ["pnpm", "dev"]
